-- ============================================================
-- Fase 6 — Almoxarifado | Seed inicial: catálogo, EPIs, ferramentas
-- Fonte: planilhas do Rodrigo em C:\Users\rodri.000\Desktop\almoxariafdo\
--   - Lista de códigos dos materiais do Almoxarifado.xlsx - Planilha1.csv
--   - Controle estoque EPI e Escritório.xlsx - EPI.csv
--   - Levantamento de Equipamento Obra Jardim Imperial.xlsx - Planilha1.csv
-- Gerado por scratchpad/gera_seed_almoxarifado.py em 11/07/2026.
-- Saldo inicial dos materiais COD001-161: [lacuna] aguardando planilha de junho
-- do Rodrigo (ver task-2-brief.md) — entra em migração *_seed_saldos.sql futura.
-- ============================================================

DO $$
DECLARE
  v_obra UUID;
  v_admin UUID;
BEGIN
  SELECT id INTO v_obra FROM obras LIMIT 1;
  SELECT id INTO v_admin FROM perfis_usuario WHERE papel = 'admin' LIMIT 1;

  -- ---------- MATERIAIS (categoria material) ----------
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD137', 'ABRAÇADEIRA 1.1/2 GOTA', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD138', 'ABRAÇADEIRA 3/4 GOTA', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD099', 'ABRAÇADEIRA GOTA 4', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD110', 'ADAPT SOLD CTO 25X3/4', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD115', 'ADAPTADOR C/ FLANGE 25 X 3/4', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD116', 'ADAPTADOR C/ FLANGE 32 X 1', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD117', 'ADAPTADOR C/ FLANGE 50 X 1.1/2', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD118', 'ADAPTADOR CURTO LR 32 X 1', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD042', 'ADESIVO PVC FR 850G', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD050', 'ANEL BORR ESG  75MM', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD049', 'ANEL BORR ESG 100MM', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD051', 'ANEL BORR ESG 50MM', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD023', 'Arame grosso', NULL, 'kg', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD022', 'Arame recozido 2 fios', NULL, 'kg', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD134', 'ARRUELA 1/4', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD100', 'BARRA ROSCADA 3MT 1/4 ZINCADA', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD103', 'BASE REG GAV 4509 B 3/4', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD104', 'BASE REG PRES 4416 3/4', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD010', 'Broca 16 encaixe tipo plus M', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD114', 'BROCA 19 BOSH', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD011', 'Broca 25 Bosh', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD008', 'Broca 6 encaixe tipo plus', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD009', 'Broca 6 p/ marteletes G', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD007', 'Broca 6 p/martelete P', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD030', 'Broxa', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD037', 'BUCHA 40X25MM', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD109', 'BUCHA RED SOLD LGA 50X25MM', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD133', 'BUCHA S8', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD089', 'CAIXA DE GORDURA TIGRE', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD130', 'CAIXA DRENO', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD079', 'CAIXA LUZ 4X4', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD080', 'CAIXA LUZ PVC 4X2', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD081', 'CAIXA LUZ PVC 4X4', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD087', 'CAIXA ORTOGONAL 4X4', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD085', 'CAIXA SIFONADA 150X150X75', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD032', 'Cola', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD083', 'CONDUITE CORRUG 1.P', '25 m = 1 unidade', 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD159', 'CONDUITE CORRUG 3/4 LARANJA', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD082', 'CONDUITE CORRUG 3X4', '50 m = 1 unidade', 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD158', 'CONDUITE CORRUG LP LARANJA', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD084', 'CONTRA UMIDADE', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD048', 'CORPO  CX SIF 150X185X75', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD047', 'CORPO CX SIF 150X150X50', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD053', 'CURVA ESG CTA 90 X 040MM', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD052', 'CURVA ESG LONGA 45 X 100MM', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD001', 'Disco de corte diamantado 110', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD013', 'Disco de corte diamantado 125', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD002', 'Disco de corte rápido G', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD004', 'Disco de corte rápido P', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD012', 'Disco lâmina serra circular M', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD005', 'Dsco de bancada serra circular', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD088', 'ELETRODUTO CORRUGADO 3/4', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD154', 'ESPOLETA', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD028', 'Estopa', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD015', 'Fita isolante', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD101', 'FITA PERFURADA 17X40X30MT', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD151', 'FLANGE DE 25MM SOLDAVEL', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD150', 'FLANGE DE 32 MM SOLDAVEL', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD149', 'FLANGE DE 50MM SOLDAVEL', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD148', 'JAQUETA E CONE 1/4', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD144', 'JOELHO 25X3/4', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD147', 'JOELHO 25X90X BL 3/4', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD136', 'JOELHO 25X90X3/4 LATÃO', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD146', 'JOELHO 40X90', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD038', 'JOELHO 45 X 25MM TIGRE', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD057', 'JOELHO ESG 45 X 040MM', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD056', 'JOELHO ESG 45 X 050MM', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD054', 'JOELHO ESG 45 X 100MM', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD059', 'JOELHO ESG 90 X 050MM TIGRE', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD058', 'JOELHO ESG 90 X 100MM', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD060', 'JOELHO ESG C/ANEL 90 X 40MM', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD039', 'JOELHO SOLD 90 X 25MM', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD119', 'JOELHO SOLD 90 X 32', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD128', 'JOELHO SOLD 90 X 40MM SEM ANEL', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD108', 'JOELHO SOLD 90X50MM', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD111', 'JOELHO SOLD B LATAO 90 25X1/2', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD055', 'JOELHO TIGRE ESG 45 X 075MM', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD064', 'JUNCAO ESG SIMPLES 040X040MM', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD063', 'JUNCAO ESG SIMPLES 050X050MM', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD072', 'JUNCAO ESG SIMPLES 100X050MM', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD061', 'JUNCAO ESG SIMPLES 100X075MM', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD062', 'JUNCAO ESG SIMPLES 100X100MM', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD003', 'Lâmina de serra circular', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD014', 'Lâmpadas', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD034', 'Lápis Carpinteiro', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD006', 'Linha de pedreiro 100m', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD040', 'LUVA 40MM', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD135', 'LUVA DE 50 SOLD', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD141', 'LUVA DE EMENDA "1"', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD142', 'LUVA DE EMENDA 3/4', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD077', 'LUVA ESG SIMP 040MM', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD074', 'LUVA ESG SIMP 050MM TIGRE', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD076', 'LUVA ESG SIMP 075MM', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD075', 'LUVA ESG SIMP 100MM', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD046', 'LUVA ROSCA 25X3/4', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD097', 'LUVA SOLD 25MM', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD096', 'LUVA SOLD 40MM', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD095', 'LUVA SOLD B LATAO 25X3/4', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD131', 'PARABOLT 1/4', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD026', 'Parafuso auto brocante 5,5x50mm', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD132', 'PARAFUSO S8', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD027', 'Pasta Lubrificante', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD139', 'PERFILADO PERFURADO 38X38', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD153', 'PINO', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD021', 'Pistola p/ pintura ar direto', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD140', 'PLUG 1/2', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD113', 'PLUG ROSCA B 3/4 333', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD129', 'PORCA 1/4', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD036', 'Prego 15x15', NULL, 'kg', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD045', 'PREGO 17X21', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD024', 'Prego 17x27', NULL, 'kg', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD025', 'Prego 18x30', NULL, 'kg', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD160', 'QUADRO ELÉTRICO', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD093', 'RALO LINEAR 50 CM FLAT GRELHA', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD094', 'RALO LINEAR 90 CM FLAT GRELHA', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD143', 'REBITE', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD086', 'REDUÇÃO 40X25', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD145', 'REDUÇÃO 50X40', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD090', 'REDUÇÃO 75X50', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD120', 'REGISTRO ESF VS. COMPACTO SOLD 25MM', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD121', 'REGISTRO ESFERA SOLD C/UNIAO 25MM', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD122', 'REGISTRO ESFERA SOLD C/UNIAO 32MM', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD123', 'REGISTRO ESFERA SOLD C/UNIAO 50MM', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD124', 'REGISTRO GAVETA 3/4 BASE DECA', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD125', 'REGISTRO PRESSAO 3/4 BASE DECA', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD031', 'Segueta', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD029', 'Sikadur', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD033', 'Solução', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD073', 'TE ESG 100X100MM TIGRE', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD092', 'TE ESG 100X50MM', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD069', 'TE ESG 40X40MM', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD070', 'TE ESG 50X50MM', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD071', 'TE ESG 75X50MM', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD107', 'TE SOLD 25MM', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD106', 'TE SOLD 50MM', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD112', 'TE SOLD B LATAO 25X1/2', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD105', 'TE SOLD RED 50X25MM', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD126', 'TEE SOLD 32', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD152', 'TELA', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD155', 'TELA ROLO', '25 m = 1 unidade', 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD102', 'TORNEIRA BOIA CAIXA D''ÁGUA 3/4', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD091', 'TRENA 5 MTS', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD078', 'TRENA 8 MTS', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD067', 'TUBO ESG SN 040MM', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD068', 'TUBO ESG SN 050MM', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD066', 'TUBO ESG SN 075MM', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD065', 'TUBO ESG SN 100MM', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD127', 'TUBO SOLD 32MM', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD098', 'TUBO SOLD PVC 25MM', '6 m = 1 unidade', 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD157', 'VDI CAIXA 30X30', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD035', 'Veda Rosca', NULL, 'un', 'material', v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, criado_por) VALUES (v_obra, 'COD161', 'VIAPLUS 1000 CX L8 K6', NULL, 'un', 'material', v_admin);

  -- ---------- EPIs (categoria epi) ----------
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, estoque_minimo, criado_por) VALUES (v_obra, 'COD162', 'ARANHA', 'ARANHA CAPACETE', 'un', 'epi', NULL, v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, estoque_minimo, criado_por) VALUES (v_obra, 'COD163', 'BONÉ', 'ÁRABE', 'un', 'epi', NULL, v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, estoque_minimo, criado_por) VALUES (v_obra, 'COD164', 'BOTINA ELETRICISTA', 'BOTINA CANO CURTO - 40', 'un', 'epi', NULL, v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, estoque_minimo, criado_por) VALUES (v_obra, 'COD165', 'BOTINA GALOCHA', 'BOTINA CANO LONGO - 38', 'un', 'epi', NULL, v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, estoque_minimo, criado_por) VALUES (v_obra, 'COD166', 'BOTINA GALOCHA', 'BOTINA CANO LONGO - 40', 'un', 'epi', NULL, v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, estoque_minimo, criado_por) VALUES (v_obra, 'COD167', 'BOTINA GALOCHA', 'BOTINA CANO LONGO - 41', 'un', 'epi', NULL, v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, estoque_minimo, criado_por) VALUES (v_obra, 'COD168', 'BOTINA GALOCHA', 'BOTINA CANO LONGO - 42', 'un', 'epi', NULL, v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, estoque_minimo, criado_por) VALUES (v_obra, 'COD169', 'BOTINA GALOCHA', 'BOTINA CANO LONGO - 44', 'un', 'epi', NULL, v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, estoque_minimo, criado_por) VALUES (v_obra, 'COD170', 'BOTINA PVC', 'BOTINA CANO CURTO - 38', 'un', 'epi', NULL, v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, estoque_minimo, criado_por) VALUES (v_obra, 'COD171', 'BOTINA PVC', 'BOTINA CANO CURTO - 39', 'un', 'epi', NULL, v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, estoque_minimo, criado_por) VALUES (v_obra, 'COD172', 'BOTINA PVC', 'BOTINA CANO CURTO - 40', 'un', 'epi', NULL, v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, estoque_minimo, criado_por) VALUES (v_obra, 'COD173', 'BOTINA PVC', 'BOTINA CANO CURTO - 41', 'un', 'epi', NULL, v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, estoque_minimo, criado_por) VALUES (v_obra, 'COD174', 'BOTINA PVC', 'BOTINA CANO CURTO - 42', 'un', 'epi', NULL, v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, estoque_minimo, criado_por) VALUES (v_obra, 'COD175', 'BOTINA PVC', 'BOTINA CANO CURTO - 43', 'un', 'epi', NULL, v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, estoque_minimo, criado_por) VALUES (v_obra, 'COD176', 'BOTINA PVC', 'BOTINA CANO CURTO - 44', 'un', 'epi', NULL, v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, estoque_minimo, criado_por) VALUES (v_obra, 'COD177', 'CAPA DE CHUVA', 'AMARELO', 'un', 'epi', NULL, v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, estoque_minimo, criado_por) VALUES (v_obra, 'COD178', 'CAPACETE', 'AMARELO', 'un', 'epi', NULL, v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, estoque_minimo, criado_por) VALUES (v_obra, 'COD179', 'CAPACETE', 'AMARELO ( USADO )', 'un', 'epi', NULL, v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, estoque_minimo, criado_por) VALUES (v_obra, 'COD180', 'CAPACETE', 'BRANCO', 'un', 'epi', NULL, v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, estoque_minimo, criado_por) VALUES (v_obra, 'COD181', 'CAPACETE', 'VERDE', 'un', 'epi', NULL, v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, estoque_minimo, criado_por) VALUES (v_obra, 'COD182', 'CINTA', 'CINTA ERGONOMICA - G', 'un', 'epi', NULL, v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, estoque_minimo, criado_por) VALUES (v_obra, 'COD183', 'CINTA', 'CINTA ERGONOMICA - M', 'un', 'epi', NULL, v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, estoque_minimo, criado_por) VALUES (v_obra, 'COD184', 'CINTA', 'CINTA ERGONOMICA - P', 'un', 'epi', NULL, v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, estoque_minimo, criado_por) VALUES (v_obra, 'COD185', 'LUVAS', 'ELETRICISTA', 'un', 'epi', NULL, v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, estoque_minimo, criado_por) VALUES (v_obra, 'COD186', 'LUVAS', 'LUVA VAQUETA', 'un', 'epi', NULL, v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, estoque_minimo, criado_por) VALUES (v_obra, 'COD187', 'LUVAS', 'NITRILICA', 'un', 'epi', NULL, v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, estoque_minimo, criado_por) VALUES (v_obra, 'COD188', 'LUVAS', 'PIGMENTADA', 'un', 'epi', NULL, v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, estoque_minimo, criado_por) VALUES (v_obra, 'COD189', 'LUVAS', 'SS-1009', 'un', 'epi', NULL, v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, estoque_minimo, criado_por) VALUES (v_obra, 'COD190', 'MÁSCARA', 'PFF2-S', 'un', 'epi', NULL, v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, estoque_minimo, criado_por) VALUES (v_obra, 'COD191', 'PROTETOR AURICULAR', 'CONCHA', 'un', 'epi', NULL, v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, estoque_minimo, criado_por) VALUES (v_obra, 'COD192', 'PROTETOR AURICULAR', 'PLUG', 'un', 'epi', NULL, v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, estoque_minimo, criado_por) VALUES (v_obra, 'COD193', 'PROTETOR SOLAR', 'PROTETOR SOLAR - 1LT', 'un', 'epi', NULL, v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, estoque_minimo, criado_por) VALUES (v_obra, 'COD194', 'TOUCA', 'BALA CLAVA', 'un', 'epi', NULL, v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, estoque_minimo, criado_por) VALUES (v_obra, 'COD195', 'UNIFORME', 'CALÇA BRIM - G', 'un', 'epi', NULL, v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, estoque_minimo, criado_por) VALUES (v_obra, 'COD196', 'UNIFORME', 'CALÇA BRIM - GG', 'un', 'epi', NULL, v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, estoque_minimo, criado_por) VALUES (v_obra, 'COD197', 'UNIFORME', 'CALÇA BRIM - M', 'un', 'epi', NULL, v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, estoque_minimo, criado_por) VALUES (v_obra, 'COD198', 'UNIFORME', 'CALÇA BRIM EXG', 'un', 'epi', NULL, v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, estoque_minimo, criado_por) VALUES (v_obra, 'COD199', 'UNIFORME', 'MANGA LONGA - EXG', 'un', 'epi', NULL, v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, estoque_minimo, criado_por) VALUES (v_obra, 'COD200', 'UNIFORME', 'MANGA LONGA - G', 'un', 'epi', NULL, v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, estoque_minimo, criado_por) VALUES (v_obra, 'COD201', 'UNIFORME', 'MANGA LONGA - GG', 'un', 'epi', NULL, v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, estoque_minimo, criado_por) VALUES (v_obra, 'COD202', 'UNIFORME', 'MANGA LONGA - M', 'un', 'epi', NULL, v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, estoque_minimo, criado_por) VALUES (v_obra, 'COD203', 'UNIFORME', 'MANGA LONGA - P', 'un', 'epi', NULL, v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, estoque_minimo, criado_por) VALUES (v_obra, 'COD204', 'UNIFORME', 'MANGA LONGA - XG', 'un', 'epi', NULL, v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, estoque_minimo, criado_por) VALUES (v_obra, 'COD205', 'UNIFORME (MESTRE DE OBRAS)', 'CALÇA JEANS - 38', 'un', 'epi', NULL, v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, estoque_minimo, criado_por) VALUES (v_obra, 'COD206', 'ÓCULOS LEOPARDO', 'PRETO', 'un', 'epi', NULL, v_admin);
  INSERT INTO materiais (obra_id, codigo, nome, descricao, und, categoria, estoque_minimo, criado_por) VALUES (v_obra, 'COD207', 'ÓCULOS LEOPARDO', 'TRANSPARENTE', 'un', 'epi', NULL, v_admin);

  -- ---------- Movimentos de inventário inicial (EPIs com saldo > 0) ----------
  INSERT INTO estoque_movimentos (obra_id, material_id, tipo, quantidade, observacao, criado_por) SELECT v_obra, id, 'entrada', 5, 'Inventário inicial (planilha EPI 11/07/2026)', v_admin FROM materiais WHERE obra_id = v_obra AND codigo = 'COD162';
  INSERT INTO estoque_movimentos (obra_id, material_id, tipo, quantidade, observacao, criado_por) SELECT v_obra, id, 'entrada', 18, 'Inventário inicial (planilha EPI 11/07/2026)', v_admin FROM materiais WHERE obra_id = v_obra AND codigo = 'COD163';
  INSERT INTO estoque_movimentos (obra_id, material_id, tipo, quantidade, observacao, criado_por) SELECT v_obra, id, 'entrada', 1, 'Inventário inicial (planilha EPI 11/07/2026)', v_admin FROM materiais WHERE obra_id = v_obra AND codigo = 'COD164';
  INSERT INTO estoque_movimentos (obra_id, material_id, tipo, quantidade, observacao, criado_por) SELECT v_obra, id, 'entrada', 3, 'Inventário inicial (planilha EPI 11/07/2026)', v_admin FROM materiais WHERE obra_id = v_obra AND codigo = 'COD170';
  INSERT INTO estoque_movimentos (obra_id, material_id, tipo, quantidade, observacao, criado_por) SELECT v_obra, id, 'entrada', 3, 'Inventário inicial (planilha EPI 11/07/2026)', v_admin FROM materiais WHERE obra_id = v_obra AND codigo = 'COD171';
  INSERT INTO estoque_movimentos (obra_id, material_id, tipo, quantidade, observacao, criado_por) SELECT v_obra, id, 'entrada', 2, 'Inventário inicial (planilha EPI 11/07/2026)', v_admin FROM materiais WHERE obra_id = v_obra AND codigo = 'COD172';
  INSERT INTO estoque_movimentos (obra_id, material_id, tipo, quantidade, observacao, criado_por) SELECT v_obra, id, 'entrada', 4, 'Inventário inicial (planilha EPI 11/07/2026)', v_admin FROM materiais WHERE obra_id = v_obra AND codigo = 'COD173';
  INSERT INTO estoque_movimentos (obra_id, material_id, tipo, quantidade, observacao, criado_por) SELECT v_obra, id, 'entrada', 2, 'Inventário inicial (planilha EPI 11/07/2026)', v_admin FROM materiais WHERE obra_id = v_obra AND codigo = 'COD174';
  INSERT INTO estoque_movimentos (obra_id, material_id, tipo, quantidade, observacao, criado_por) SELECT v_obra, id, 'entrada', 2, 'Inventário inicial (planilha EPI 11/07/2026)', v_admin FROM materiais WHERE obra_id = v_obra AND codigo = 'COD175';
  INSERT INTO estoque_movimentos (obra_id, material_id, tipo, quantidade, observacao, criado_por) SELECT v_obra, id, 'entrada', 2, 'Inventário inicial (planilha EPI 11/07/2026)', v_admin FROM materiais WHERE obra_id = v_obra AND codigo = 'COD176';
  INSERT INTO estoque_movimentos (obra_id, material_id, tipo, quantidade, observacao, criado_por) SELECT v_obra, id, 'entrada', 7, 'Inventário inicial (planilha EPI 11/07/2026)', v_admin FROM materiais WHERE obra_id = v_obra AND codigo = 'COD177';
  INSERT INTO estoque_movimentos (obra_id, material_id, tipo, quantidade, observacao, criado_por) SELECT v_obra, id, 'entrada', 2, 'Inventário inicial (planilha EPI 11/07/2026)', v_admin FROM materiais WHERE obra_id = v_obra AND codigo = 'COD178';
  INSERT INTO estoque_movimentos (obra_id, material_id, tipo, quantidade, observacao, criado_por) SELECT v_obra, id, 'entrada', 2, 'Inventário inicial (planilha EPI 11/07/2026)', v_admin FROM materiais WHERE obra_id = v_obra AND codigo = 'COD179';
  INSERT INTO estoque_movimentos (obra_id, material_id, tipo, quantidade, observacao, criado_por) SELECT v_obra, id, 'entrada', 2, 'Inventário inicial (planilha EPI 11/07/2026)', v_admin FROM materiais WHERE obra_id = v_obra AND codigo = 'COD181';
  INSERT INTO estoque_movimentos (obra_id, material_id, tipo, quantidade, observacao, criado_por) SELECT v_obra, id, 'entrada', 2, 'Inventário inicial (planilha EPI 11/07/2026)', v_admin FROM materiais WHERE obra_id = v_obra AND codigo = 'COD182';
  INSERT INTO estoque_movimentos (obra_id, material_id, tipo, quantidade, observacao, criado_por) SELECT v_obra, id, 'entrada', 1, 'Inventário inicial (planilha EPI 11/07/2026)', v_admin FROM materiais WHERE obra_id = v_obra AND codigo = 'COD183';
  INSERT INTO estoque_movimentos (obra_id, material_id, tipo, quantidade, observacao, criado_por) SELECT v_obra, id, 'entrada', 2, 'Inventário inicial (planilha EPI 11/07/2026)', v_admin FROM materiais WHERE obra_id = v_obra AND codigo = 'COD184';
  INSERT INTO estoque_movimentos (obra_id, material_id, tipo, quantidade, observacao, criado_por) SELECT v_obra, id, 'entrada', 3, 'Inventário inicial (planilha EPI 11/07/2026)', v_admin FROM materiais WHERE obra_id = v_obra AND codigo = 'COD185';
  INSERT INTO estoque_movimentos (obra_id, material_id, tipo, quantidade, observacao, criado_por) SELECT v_obra, id, 'entrada', 16, 'Inventário inicial (planilha EPI 11/07/2026)', v_admin FROM materiais WHERE obra_id = v_obra AND codigo = 'COD186';
  INSERT INTO estoque_movimentos (obra_id, material_id, tipo, quantidade, observacao, criado_por) SELECT v_obra, id, 'entrada', 27, 'Inventário inicial (planilha EPI 11/07/2026)', v_admin FROM materiais WHERE obra_id = v_obra AND codigo = 'COD187';
  INSERT INTO estoque_movimentos (obra_id, material_id, tipo, quantidade, observacao, criado_por) SELECT v_obra, id, 'entrada', 12, 'Inventário inicial (planilha EPI 11/07/2026)', v_admin FROM materiais WHERE obra_id = v_obra AND codigo = 'COD188';
  INSERT INTO estoque_movimentos (obra_id, material_id, tipo, quantidade, observacao, criado_por) SELECT v_obra, id, 'entrada', 17, 'Inventário inicial (planilha EPI 11/07/2026)', v_admin FROM materiais WHERE obra_id = v_obra AND codigo = 'COD189';
  INSERT INTO estoque_movimentos (obra_id, material_id, tipo, quantidade, observacao, criado_por) SELECT v_obra, id, 'entrada', 48, 'Inventário inicial (planilha EPI 11/07/2026)', v_admin FROM materiais WHERE obra_id = v_obra AND codigo = 'COD190';
  INSERT INTO estoque_movimentos (obra_id, material_id, tipo, quantidade, observacao, criado_por) SELECT v_obra, id, 'entrada', 11, 'Inventário inicial (planilha EPI 11/07/2026)', v_admin FROM materiais WHERE obra_id = v_obra AND codigo = 'COD192';
  INSERT INTO estoque_movimentos (obra_id, material_id, tipo, quantidade, observacao, criado_por) SELECT v_obra, id, 'entrada', 2, 'Inventário inicial (planilha EPI 11/07/2026)', v_admin FROM materiais WHERE obra_id = v_obra AND codigo = 'COD193';
  INSERT INTO estoque_movimentos (obra_id, material_id, tipo, quantidade, observacao, criado_por) SELECT v_obra, id, 'entrada', 2, 'Inventário inicial (planilha EPI 11/07/2026)', v_admin FROM materiais WHERE obra_id = v_obra AND codigo = 'COD194';
  INSERT INTO estoque_movimentos (obra_id, material_id, tipo, quantidade, observacao, criado_por) SELECT v_obra, id, 'entrada', 6, 'Inventário inicial (planilha EPI 11/07/2026)', v_admin FROM materiais WHERE obra_id = v_obra AND codigo = 'COD196';
  INSERT INTO estoque_movimentos (obra_id, material_id, tipo, quantidade, observacao, criado_por) SELECT v_obra, id, 'entrada', 5, 'Inventário inicial (planilha EPI 11/07/2026)', v_admin FROM materiais WHERE obra_id = v_obra AND codigo = 'COD198';
  INSERT INTO estoque_movimentos (obra_id, material_id, tipo, quantidade, observacao, criado_por) SELECT v_obra, id, 'entrada', 3, 'Inventário inicial (planilha EPI 11/07/2026)', v_admin FROM materiais WHERE obra_id = v_obra AND codigo = 'COD199';
  INSERT INTO estoque_movimentos (obra_id, material_id, tipo, quantidade, observacao, criado_por) SELECT v_obra, id, 'entrada', 12, 'Inventário inicial (planilha EPI 11/07/2026)', v_admin FROM materiais WHERE obra_id = v_obra AND codigo = 'COD201';
  INSERT INTO estoque_movimentos (obra_id, material_id, tipo, quantidade, observacao, criado_por) SELECT v_obra, id, 'entrada', 1, 'Inventário inicial (planilha EPI 11/07/2026)', v_admin FROM materiais WHERE obra_id = v_obra AND codigo = 'COD202';
  INSERT INTO estoque_movimentos (obra_id, material_id, tipo, quantidade, observacao, criado_por) SELECT v_obra, id, 'entrada', 2, 'Inventário inicial (planilha EPI 11/07/2026)', v_admin FROM materiais WHERE obra_id = v_obra AND codigo = 'COD204';
  INSERT INTO estoque_movimentos (obra_id, material_id, tipo, quantidade, observacao, criado_por) SELECT v_obra, id, 'entrada', 3, 'Inventário inicial (planilha EPI 11/07/2026)', v_admin FROM materiais WHERE obra_id = v_obra AND codigo = 'COD205';
  INSERT INTO estoque_movimentos (obra_id, material_id, tipo, quantidade, observacao, criado_por) SELECT v_obra, id, 'entrada', 19, 'Inventário inicial (planilha EPI 11/07/2026)', v_admin FROM materiais WHERE obra_id = v_obra AND codigo = 'COD206';
  INSERT INTO estoque_movimentos (obra_id, material_id, tipo, quantidade, observacao, criado_por) SELECT v_obra, id, 'entrada', 22, 'Inventário inicial (planilha EPI 11/07/2026)', v_admin FROM materiais WHERE obra_id = v_obra AND codigo = 'COD207';

  -- ---------- FERRAMENTAS (itens individuais numerados) ----------
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Enxada 01', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Enxada 02', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Enxada 03', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Enxada 04', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Enxada 05', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Enxada 06', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Enxada 07', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Pá 01', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Pá 02', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Pá 03', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Pá 04', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Pá 05', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Pá 06', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Pá 07', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Picareta 01', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Picareta 02', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Picareta 03', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Marreta Grande 01', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Marreta Pequena 01', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Martelo 01', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Martelo 02', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Martelo 03', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Regua 2 metros 01', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Regua 2 metros 02', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Regua 2 metros 03', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Regua 2 metros 04', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Regua 2 metros 05', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Regua 2 metros 06', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Regua 2 metros 07', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Regua 2 metros 08', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Régua 1 metro 01', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Régua 1 metro 02', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Masseira 01', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Masseira 02', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Masseira 03', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Masseira 04', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Masseira 05', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Masseira 06', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Cavadeira Grande 01', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Cavadeira Pequena 01', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Extenção 01', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Extenção 02', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Extenção 03', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Carrinho de mão 01', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Carrinho de mão 02', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Carrinho de mão 03', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Carrinho de mão 04', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Furadeira de Impacto 01', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Furadeira de Impacto 02', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Lixadeira pequena 01', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Tesoura Grande 01', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Campressor de Ar 01', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Graxeira 01', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Lavadora de Alta Pressão 01', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Parafusadeira 01', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Labanca 01', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Labanca 02', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Turquesa 01', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Turquesa 02', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Turquesa 03', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Turquesa 04', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Turquesa 05', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Turquesa 06', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Enxadão 01', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Enxadão 02', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Nivel a laser 01', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Nível de Mão 01', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Nível de Mão 02', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Peneira 01', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Betoneira 01', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Betoneira 02', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Vibrador 01', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Vibrador 02', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Mangueira de Nível 01', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Mangueira de Jardim 01', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Mangueira de Jardim 02', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Ponteiro 01', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Ponteiro 02', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Ponteiro 03', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Chave de dobrar ferro 01', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Chave de Bomba d''água 01', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Picola 01', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Picola 02', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Cavador 01', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Cavador 02', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Makita 01', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Makita 02', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Andaime 01', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Andaime 02', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Andaime 03', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Andaime 04', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Andaime 05', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Andaime 06', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Andaime 07', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Andaime 08', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Andaime 09', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Andaime 10', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Andaime 11', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Andaime 12', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Andaime 13', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Andaime 14', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Andaime 15', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Andaime 16', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Andaime 17', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Andaime 18', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Andaime 19', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Andaime 20', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Andaime 21', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Andaime 22', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Andaime 23', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Andaime 24', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Andaime 25', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Andaime 26', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Andaime 27', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Andaime 28', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Andaime 29', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Andaime 30', v_admin);
  INSERT INTO ferramentas (obra_id, nome, criado_por) VALUES (v_obra, 'Tesoura pequena 01', v_admin);
END $$;
